apiVersion: v1
kind: Pod
metadata:
  name: service-a-after
  labels:
    app: service-a-after
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: us.icr.io/cascon-2019-k8s-security/service-a-after
    name: service-a-before

