apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-service-b
  namespace: org-1
spec:
  podSelector:
    matchLabels:
      app: service-b
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: service-a          
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-service-a
  namespace: org-1
spec:
  podSelector: 
    matchLabels:
      app: service-a
  policyTypes:
  - Ingress


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-namespace-org2
  namespace: org-2
spec:
  podSelector: 
    matchLabels:
      app: service-c
  policyTypes:
  - Ingress
  - Egress

