apiVersion: v1
kind: Pod
metadata:
  name: secret-vol
spec:
  containers:
  - name: secret-vol
    image: us.icr.io/cason2019kb/service-a
    volumeMounts:
    - name: secrets
      mountPath: "/etc/mysecret"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: mysecret