apiVersion: v1
kind: Pod
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: us.icr.io/cascon-2019-k8s-security/service-c
    name: service-c

