apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      name: service-c
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: us.icr.io/cascon-2019-k8s-security/service-c
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: default-us-icr-io