apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      name: service-b
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: us.icr.io/cascon-2019-k8s-security/service-b
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: default-us-icr-io