
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: org-1-rolebinding
  namespace: org-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kb-security
subjects:
- kind: ServiceAccount
  name: org-1-service-account
  namespace: org-1


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: org-2-rolebinding
  namespace: org-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kb-security
subjects:
- kind: ServiceAccount
  name: org-2-service-account
  namespace: org-2
