apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-cascon
roleRef:
  kind: ClusterRole
  name: psp-cascon
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: dev
  namespace: dev

#   Authorize specific service accounts:
# - kind: ServiceAccount
#   name: <authorized service account name>
#   namespace: <authorized pod namespace>

#   Authorize specific users (not recommended):
# - kind: User
#   apiGroup: rbac.authorization.k8s.io
#   name: <authorized user name>

#   # Authorize all service accounts in a namespace:
# - kind: Group
#   apiGroup: rbac.authorization.k8s.io
#   name: system:serviceaccounts

# # Or equivalently, all authenticated users in a namespace:
# - kind: Group
#   apiGroup: rbac.authorization.k8s.io
#   name: system:authenticated