---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: service-a
          servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: us.icr.io/cascon-2019-k8s-security/service-a
    name: service-a
    resources:
      requests:
        memory: "2G"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 3
      periodSeconds: 3
      

  